### ISSUE TITLE
INVALID_PERMISSION when trying to withdraw

### ISSUE THREAD

**Issue by AriEi4** [ericsomdahl/python-bittrex#100]
After successful login:
```
from bittrex import Bittrex
my_bittrex = Bittrex('', '')
balances = my_bittrex.get_balances()
x = my_bittrex.withdraw('BTC', 1, '')
print('done')
```
I get the balances in 'balances', but in 'x' I get:
{u'message': u'INVALID_PERMISSION', u'result': None, u'success': False}

Python 2.7, any ideas?

**Comment by skyl** [comment]
Did you enable deposits and withdrawals for your API key in the Bittrex interface?

**Comment by AriEi4** [comment]
Nope.
Is there any way to do it with the API and not with the web interface?

**Comment by ericsomdahl** [comment]
no, you must login to the web interface to set permissions
