### ISSUE TITLE
get_markets still in V0.2.2 release

### ISSUE THREAD

**Issue by Corwin99** [ericsomdahl/python-bittrex#105]
Notes on https://github.com/ericsomdahl/python-bittrex/releases for V0.2.2 indicate that 
   get_markets
   get_marketsummary
has been pulled, but they are present in the V0.2.2 release that I just installed using
    python -m pip install python-bittrex --upgrade

**Comment by skyl** [comment]
It's present if you are using the default 1.X API, as I understand it.

**Comment by ericsomdahl** [comment]
yep, that is an artifact of how we're doing API 1.1 compatibility.  Calls to those methods while using a connector configured to use V2.0 will raise runtime exceptions
