### ISSUE TITLE
ImportError: No module named bittrex

### ISSUE THREAD

**Issue by fabius8** [ericsomdahl/python-bittrex#106]
```
#!/usr/bin/env python

from bittrex.bittrex import Bittrex, API_V2_0

my_bittrex = Bittrex(None, None, api_version=API_V2_0)
my_bittrex.get_markets()
```

$ ./bittrex.py
Traceback (most recent call last):
  File "./bittrex.py", line 3, in <module>
    from bittrex.bittrex import Bittrex, API_V2_0
  File "/home/ubuntu/autotrade/bittrex.py", line 3, in <module>
    from bittrex.bittrex import Bittrex, API_V2_0
ImportError: No module named bittrex

**Comment by TalhaAsmal** [comment]
Hi,

Did you install using pip into your active virtual environment?

**Comment by fabius8** [comment]
Hi,
Yes, I already install it.  please check the log blew
```
➜  github pip install python-bittrex
Requirement already satisfied: python-bittrex in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: requests in /usr/local/lib/python2.7/site-packages (from python-bittrex)
```

**Comment by slazarov** [comment]
What’s in your init.py?

**Comment by fabius8** [comment]
```
➜  bittrex pwd
/usr/local/lib/python2.7/site-packages/bittrex
➜  bittrex cat __init__.py
from .bittrex import *          # noqa
➜  bittrex ls
__init__.py  __init__.pyc bittrex.py   bittrex.pyc
```

**Comment by TalhaAsmal** [comment]
Are you running it with python2 or python3? It seems you've installed it with python2, so that should be the version you use when importing bittrex.

**Comment by fabius8** [comment]
I run it with python2.7. and pip version is 2.7 too.

**Comment by skyl** [comment]
Is it that the name of your script is `bittrex.py` and that is conflicting with the library name?

**Comment by fabius8** [comment]
Hi , I rename `bittrex.py` to `hi_bittrex.py`, It is OK now! thank you very much!
