### ISSUE TITLE
TIMEINEFFECT_FILL_OR_KILL

### ISSUE THREAD

**Issue by music** [ericsomdahl/python-bittrex#112]
Using TIMEINEFFECT_FILL_OR_KILL in trade_buy or trade_sell is throwing the following error: 

{'message': 'There was a problem processing your request. If this problem persists, please email support@bittrex.com with this order id.'} 

Is something going wrong with this call? It works perfectly fine with TIMEINEFFECT_IMMEDIATE_OR_CANCEL but fails with the fill or kill.

**Comment by bitqistchris** [comment]
I can't get it working as well. Did you manage to fix it?

**Comment by music** [comment]
No, unfortunately I did not. I think it's a problem with bittrex's API not offering support for that call.
