### ISSUE TITLE
Nonce Not Provided

### ISSUE THREAD

**Issue by RaghuC99** [ericsomdahl/python-bittrex#119]
Hi,
Here is a little snippet of my code:

bapi = Bittrex(bittrex_key, bittrex_secret)

balance = 0

def updateBalance():
	global balance
	balance = bapi.get_balance("BTC")['result']['Available']
	print(balance, "BTC left.")

updateBalance()

However, when running the api call, it is returning "none" because Nonce is not provided. I don't see a place to enter the nonce in the function arguments/parameters, and I tried changing it in bittrex.py, but no luck. Can someone please help me? thanks

**Comment by skyl** [comment]
Are your credentials valid?

```
In [9]: b = Bittrex(None, None)

In [10]: b.get_balance('BTC')
Out[10]: {'message': 'APIKEY_INVALID', 'result': None, 'success': False}
```

**Comment by RaghuC99** [comment]
Thanks skyl. I spent hours trying to change the source code bittrex.py but just realized I had an extra space in my API key. :)

**Comment by skyl** [comment]
No problemo.

**Comment by maheshmnj** [comment]
which key do we need to insert(secret or key) to get the balance in json format  through this url
https://bittrex.com/api/v1.1/account/getbalances?apikey=API_KEY

**Comment by gaethofs** [comment]
You need to add an *apisign* header param ( `hash_hmac('sha512', $url, <private key>)`  )and use the public key in het url
