### ISSUE TITLE
getorderhistory missing

### ISSUE THREAD

**Issue by robby-dermody** [ericsomdahl/python-bittrex#12]
'getorderhistory' is missing from this line: https://github.com/ericsomdahl/python-bittrex/blob/master/bittrex/bittrex.py#L19

**Comment by ericsomdahl** [comment]
thanks -- I have been busy with other projects and have neglected this codebase a bit. A fix for this was specified in issue #10 a while ago.  I will try to get to this soon.

Of course, a PR with that patch applied would be appreciated too :smile:

**Comment by ericsomdahl** [comment]
fixed by #16
