### ISSUE TITLE
Inconsistent Naming Convention `get_market_summaries` and `get_marketsummary`

### ISSUE THREAD

**Issue by codesw1tch** [ericsomdahl/python-bittrex#125]
This I guess is a question of coding style, but it seems to me that the functions `get_market_summaries` and `get_marketsummary` are inconsistently named...

I propose that a more consistent naming convention is either `[get_market_summaries, get_market_summary]`, or `[get_marketsummaries, get_marketsummary]`

**Comment by robaleman** [comment]
`get_market_summary` +`'get_market_summaries` seems to be the one that's more consistent with the current naming convention!

**Comment by ericsomdahl** [comment]
I'm ok with this.  PRs are welcome

**Comment by codesw1tch** [comment]
Happy to submit a PR, thanks!

**Comment by skyl** [comment]
Looks like this is merged. Reopen if I'm wrong.
