### ISSUE TITLE
Latest Candle

### ISSUE THREAD

**Issue by haythamabutair** [ericsomdahl/python-bittrex#126]
When trying to get the latest candle for a given market, I receive the following:

self.my_bittrex_2.get_latest_candle(market, 'oneMin')
viewitems(): 
[u'C']: 1.159e-05
[u'H']: 1.16e-05
[u'L']: 1.155e-05
[u'O']: 1.156e-05
[u'BV']: 0.68619237
[u'T']: u'2018-01-12T22:05:00'
[u'V']: 59245.2128589
[u'success']: True

what exactly does 'BV' stand for? 

Is 'V' the current traded volume for that minute? Or the total volume in the market?

Thanks in advance!

**Comment by robaleman** [comment]
Hey mate. V refers to 'volume' while BV refers to 'base volume'. Volume refers to the amount of that currency that has been traded in that candle (ie, if your market is 'BTC-XRP', then it would be the amount of XRP bought or sold), while base volume refers to the total value traded in the base currency (ie, if your market is 'BTC-XRP', then it would be the BTC amount traded in that particular market).

**Comment by haythamabutair** [comment]
@robaleman  - Makes perfect sense. Thanks mate!

If anything comes up, i'll follow up on this thread.

**Comment by haythamabutair** [comment]
@robaleman - Just a quick follow up. Is there a way to get my sell/buy order to be on the first to execute? I see there is a queue depending on who placed it first. Worth a shot to ask :)

**Comment by robaleman** [comment]
@haythamabutair Sorry, not sure man. I don't really work with buy/sell calls.

**Comment by ericsomdahl** [comment]
@haythamabutair nope - the bittrex execution engine does what it pleases.  the only concrete thing you can do to get faster execution is submit a better price
