### ISSUE TITLE
SOS help getOpenOrders

### ISSUE THREAD

**Issue by emanuelecesari** [ericsomdahl/python-bittrex#13]
Hello i am a young developer this is my first time with the api of bittrex,  I am developing a python bot for bittrex,  but is all the day that i try to make a request to get the open order.
 My code is very similar to your but I dont know, why it dosent works the request status is 200 but this is the reply:
{'success': False, 'message': 'INVALID_SIGNATURE', 'result': None}
this is my code:
 ```
def getOpenOrders(self,url, market):
        
        nonce = int(time.time())
        urlrequest = url + '?apikey=' + self.apiKey + '&nonce=' +str(nonce)
        
        
        signature = hmac.new(self.Secret.encode(), urlrequest.encode(), hashlib.sha512).hexdigest()

        parameter = {
            'market':market,        
        }
        headers = {
            'apisign': signature
        }
        self.r = requests.get(urlrequest,parameter, headers= headers)
        print(self.r.url)
        print(self.r.json())
```
Could you please help me?

**Comment by ericsomdahl** [comment]
Hi Emanuel,

Are you able to successfully call any of the other methods that require authentication? (like getbalance or getbalances)

The invalid signature could be the result of not specifying the API Key correctly.  Do you have your secret.json setup?

**Comment by emanuelecesari** [comment]
i have fixed for my self was problem with hmac function 
 thank you so  much!

**Comment by mfurlend** [comment]
`signature = hmac.new(self.secret, url, hashlib.sha512).hexdigest()`

should be

`signature = hmac.new(bytearray(self.secret, 'utf8'), url.encode(), hashlib.sha512).hexdigest()`

**Comment by ericsomdahl** [comment]
@JoeLiberi @mfurlend which version of the repo are you guys using?  The code on HEAD of master right now is
```
apisign = hmac.new(self.api_secret.encode(), 
   request_url.encode(),  
   hashlib.sha512).hexdigest()
```

I can maybe see explicitly specifying the UTF-8 encoding, but the other args are already being encoded.
