### ISSUE TITLE
No response from bittrex server

### ISSUE THREAD

**Issue by lenhhoxung86** [ericsomdahl/python-bittrex#135]
Hello, 
I'm using your lib to communicate with bittrex server.
Here is how I get the order history:

```
bittrex = Bittrex(API_KEY,API_SECRET)
data = bittrex.get_order_history()
```

On my laptop, it returns:
`{'success': False, 'message': 'NO_API_RESPONSE', 'result': None}`

However, if I run the code on a droplet server (digital ocean), it returns the correct data containing all history orders.
Previously, the code worked on my laptop, but it suddenly stopped working.
I don't know what the cause is.
Please help, thank you.

**Comment by ericsomdahl** [comment]
is this still an issue?  Please re-open if necessary

**Comment by lenhhoxung86** [comment]
Yep, it still happens, even now with my droplet server.
Other functions are working fine, like `get_order_history` or `get_withdrawal_history`
