### ISSUE TITLE
get_markets for V2 API in master branch

### ISSUE THREAD

**Issue by luisomar3** [ericsomdahl/python-bittrex#137]
The get_markets function for V2 API is only available on the support branch of V2. If you install python-bittrex from PIP you have to manually add the code yourself.

**Comment by ericsomdahl** [comment]
last I checked the get_markets call was not available against the 2.0 API endpoints.  What is the correct 2.0 URL to hit for that?

**Comment by ericsomdahl** [comment]
I lifted this URL from the golang connector wiki:

https://bittrex.com/api/v2.0/pub/markets/GetMarkets?_=1500913483670

But it 404s.  Is there a new one you know about?

**Comment by luisomar3** [comment]
Yes you're right. I was confusing the methods name that I call in my script.
