### ISSUE TITLE
Is this repo still being maintained?

### ISSUE THREAD

**Issue by ekerstein** [ericsomdahl/python-bittrex#18]
Is this repo still being maintained? Just want to check before using it in my code.

On the Bittrex API page it says: "V1 will be deprecated on 7/20. Please move to V1.1 immediately". Does that affect this code at all or has it been transitioned?

**Comment by ericsomdahl** [comment]
Yep, we are still open for business.  We did the 1.1 migration last year.   This repo doesn't need much in the way of maintenance since the Bittrex API is pretty stable.
