### ISSUE TITLE
INVALID_SIGNATURE

### ISSUE THREAD

**Issue by mrubinst** [ericsomdahl/python-bittrex#23]
The program below (with 'key' and 'secret' as provided by bittrex) produces as output INVALID_SIGNATURE. Any idea why?

Here is the program:

#!/usr/bin/env python
from bittrex import bittrex
api = bittrex('key', 'secret')
balance = api.getbalance('BTC')
print balance

**Comment by Felipeforerome** [comment]
Hi mrubinst!
Did you manage to solve this problem? I'm getting it too

**Comment by Felipeforerome** [comment]
Hi! I figured out what was wrong, I wrote de key wrong.
Hope it helps you

**Comment by mrubinst** [comment]
I managed to fix the problem by creating, on bittrex, a new key pair with the permissions I needed. I don't think I did anything wrong the first time (when I was getting the INVALID_SIGNATURE)- I think I did cut and paste the key pair correctly the first time around. The one thing I did differently the first time was I changed the permissions after I had already created the key pair. But I can't imagine that would be an issue (on the bittrex side). Anyhow, it's all working great now, so this issue is closed for me. Thanks Eric for your code.

**Comment by tarun1475** [comment]
Look at this function it is working fine for me and tested.

function calculateSign(url){
	var sign=crypto.createHmac('sha512',constants.bittrexCredentials.SECRET); 

	sign = sign.update(url,'ascii');
	sign = sign.digest('hex');
	return sign;
}
Full Implementation repo : https://github.com/tarun1475/Nodejs-Bittrex-Client
