### ISSUE TITLE
get_order_history() doesn't load entire history

### ISSUE THREAD

**Issue by ekerstein** [ericsomdahl/python-bittrex#25]
I use a simple python script that pulls my orders every couple hours and counts them. I noticed that over the last hour my cumulative orders have somehow started going down. I'm simply pulling get_order_history() and counting up the result array.

If I go on Bittrex to my orders page and download my full order history it's different than what i'm getting from get_order_history(). Is there some sort of cap or limit on the amount of data pulled?

Can someone else test this for their own trade history?

**Comment by gleblanc1783** [comment]
+1 confirmed.

It's missing a bunch of data passed a certain date.

**Comment by jephir** [comment]
Also missing history past a certain date when using the Bittrex REST API directly.

**Comment by gilllambrigts** [comment]
Unfortunately, that's a big limitation in the Bittrex API. Currently the API only returns transaction made in the last month. You can, however, manually download the CSV file of all your transactions. I know this 'solution' sucks big time, but it's the only one. 

To download the CSV, go to Orders and navigate to the bottom table that says completed. Just on top of the table to the right, there is a button called 'CSV'.

**Comment by ericsomdahl** [comment]
@gilllambrigts this is the solution, unfortunately. :unamused:
