### ISSUE TITLE
How to get historical data?

### ISSUE THREAD

**Issue by techietrader** [ericsomdahl/python-bittrex#30]
Hi there,
Thanks for the wrapper. Its nicely designed and easy to understand.

I was going through the api page on Bittrex's site and then this python wrapper here. They have nothing to fetch historical OHLC data for any period, do they?

Is there any way?

Regards,

**Comment by ezredd** [comment]
There is not, you need to record it by yourself. You can purchase from third parties though like coinigy eg.

**Comment by ericsomdahl** [comment]
try these Kaggle links for data:
[Bitcoin](https://www.kaggle.com/mczielinski/bitcoin-historical-data)
[Ethereum](https://www.kaggle.com/kingburrito666/ethereum-historical-data)
