### ISSUE TITLE
Cannot get buy limit to work 

### ISSUE THREAD

**Issue by Domebone** [ericsomdahl/python-bittrex#34]
I cannot figure out what I am doing wrong to not be able to do buy_limit, any help is appreciated! 

from bittrex import Bittrex

api = Bittrex('0c7axxxxxx197d4ac5aa', 'fce8a5xxxxx245a4d81ac10')
#getting BTCBalance
trade = 'BTC'
pumpcurrency = raw_input('which currency would you like to pump?')
market = '{0}-{1}'.format(trade, pumpcurrency)

BTCbalance = api.get_balance(trade)['result']['Available']
print "Your balance is {0} {1}.".format(BTCbalance, trade)

# Getting the BTC price for your pumpable currency
cryptosummary = api.getmarketsummary(market)
currencyprice = cryptosummary['result'][0]['Last']
print 'The price for {0} is {1:.8f} {2}.'.format(pumpcurrency, currencyprice, trade)

# Amount of coins to buy
amount = BTCbalance/currencyprice

# How big of a profit you want to make
multiplier = 1+ float(raw_input("How much profit would you like to make? (input percentage as integer)"))/100
print ("Selling at "+str(multiplier) +"x profit")

# Buying the pump currency for BTC

api.buy_limit(market, amount, currencyprice)
print ('Buying ' +str(amount)+" "+ pumpcurrency + ' at ' + str(currencyprice) + " each.")

**Comment by Munkeynutz** [comment]
There's a lot wrong here...you seem to understand the basic idea of using the ,JSON as a list but lack the proper implementation. 
Also you need to examine your usage of quotation marks.

**Comment by Domebone** [comment]
Hi,

Is there any way you could be more specific with some examples?

Best,

Ryszard


________________________________

**Comment by ericsomdahl** [comment]
i'm closing this issue, PEBKAC
