### ISSUE TITLE
Can you please add this parameter in The Buy Limit Method on V2.0

### ISSUE THREAD

**Issue by mynksngh** [ericsomdahl/python-bittrex#35]
Dear,

  Can you please check this is working with v2.0 , bit its not supported on v1.1
{ TimeInEffect=IMMEDIATE_OR_CANCEL }

**Comment by ericsomdahl** [comment]
I prefer to wait until the 2.0 API is out of beta.  At that time we will upgrade everything necessary.

**Comment by skyl** [comment]
Is the 2.0 api documented by Bittrex anywhere? I can't seem to find it.

**Comment by llazzaro** [comment]
I sent an email to bittrex and I think we will have a very long "beta".
the current web is using the new api I manage to debug the requests.

**Comment by llazzaro** [comment]
Here are the endpoints:
`

https://bittrex.com/api/v2.0/key/balance/getbalances 
https://bittrex.com/api/v2.0/key/balance/getbalance?currencyname=BTC 
https://bittrex.com/api/v2.0/key/balance/getpendingwithdrawals?currencyname=BTC 
https://bittrex.com/api/v2.0/key/balance/getwithdrawalhistory?currencyname=BTC 
https://bittrex.com/api/v2.0/key/balance/getpendingdeposits?currency=BTC 
https://bittrex.com/api/v2.0/key/balance/getdeposithistory?currency=BTC 
https://bittrex.com/api/v2.0/key/balance/getdepositaddress?currency=BTC 
https://bittrex.com/api/v2.0/key/balance/generatedepositaddress?currency=BTC 
https://bittrex.com/api/v2.0/key/balance/withdrawcurrency?currency=BTC&quantity=1&address=xxxxx 
​ 
​ 
https://bittrex.com/api/v2.0/key/market/tradesell?marketname=BTC-LTC&ordertype=XXXX&quantity=1&rate=.00000012&timeInEffect=IOC&conditiontype=xxx&target=xxxx 
https://bittrex.com/api/v2.0/key/market/tradebuy?marketname=BTC-LTC&ordertype=XXXX&quantity=1&rate=.00000012&timeInEffect=IOC&conditiontype=xxx&target=xxxx 
https://bittrex.com/api/v2.0/key/market/cancel?orderid=xxxx 
https://bittrex.com/api/v2.0/key/market/getopenorders?marketname=BTC-LTC 
https://bittrex.com/api/v2.0/key/market/getorderhistory?marketname=BTC-LTC 
​ 
https://bittrex.com/api/v2.0/key/orders/getorder?orderid=xxx 
https://bittrex.com/api/v2.0/key/orders/getopenorders 
https://bittrex.com/api/v2.0/key/orders/getorderhistory 
​ 
https://bittrex.com/api/v2.0/pub/Markets/GetMarketSummaries 
https://bittrex.com/api/v2.0/pub/Currencies/GetCurrencies 
https://bittrex.com/api/v2.0/pub/Currencies/GetWalletHealth 
https://bittrex.com/api/v2.0/pub/Currency/GetBalanceDistribution 
https://bittrex.com/api/v2.0/pub/Markets/GetMarketSummaries 
https://bittrex.com/api/v2.0/pub/Currencies/GetCurrencies 
https://bittrex.com/api/v2.0/pub/Currencies/GetWalletHealth 
https://bittrex.com/api/v2.0/pub/Currency/GetBalanceDistribution 
https://bittrex.com/api/v2.0/pub/Market/GetMarketSummary 
https://bittrex.com/api/v2.0/pub/Market/GetMarketOrderBook 
https://bittrex.com/api/v2.0/pub/Market/GetMarketHistory 
https://bittrex.com/api/v2.0/pub/Markets/GetMarkets 
https://bittrex.com/api/v2.0/pub/Markets/GetMarketSummaries 
https://bittrex.com/api/v2.0/pub/Currencies/GetCurrencies 
https://bittrex.com/api/v2.0/pub/Currencies/GetWalletHealth 
https://bittrex.com/api/v2.0/pub/Currency/GetBalanceDistribution

Some order info

OrderType

LIMIT, 
MARKET,

TimeInEffect

GOOD_TIL_CANCELLED, 
IMMEDIATE_OR_CANCEL, 
FILL_OR_KILL

ConditionType

NONE, 
GREATER_THAN, 
LESS_THAN, 
STOP_LOSS_FIXED, 
STOP_LOSS_PERCENTAGE

Here is a proper buy uri.

https://bittrex.com/api/v2.0/key/market/TradeBuy?marketName=BTC-LTC&orderType=LIMIT&quantity=5000&rate=.00000012&timeInEffect=GOOD_TIL_CANCELLED&conditionType=NONE&target=0

conditionType and target are required,I just set target to 0 for a none conditional and it works fine.

You would use TradeSell for a sell.`

**Comment by ericsomdahl** [comment]
I have started work on support for API 2.0.  What is done so far has been pushed to a branch.

The plumbing is mostly complete, just updating the existing methods to work with the new mechanism and adding the new endpoints for 2.0

**Comment by mugdhashinde** [comment]
I am trying to use buylimit api but getting error {"success":false,"message":"APISIGN_NOT_PROVIDED","result":null}. There is no documentation which provides details on this APISIGN_NOT_PROVIDED.

**Comment by zmarcoz** [comment]
From above, I see the following URL.

I do not understand of this market buy order. 

I changed the order time from LIMIT to MARKET.

However, what is the rate? Market buy should buy at the best available rate. Why I need to set the rate? I tested without the rate. but it does not work.  

"The server returned the status 400 with message "Bad Request" in response to the request to URL"
=================================

Here is a proper buy uri.

https://bittrex.com/api/v2.0/key/market/TradeBuy?marketName=BTC-LTC&orderType=LIMIT&quantity=5000&rate=.00000012&timeInEffect=GOOD_TIL_CANCELLED&conditionType=NONE&target=0

**Comment by StasTukalo** [comment]
Hi! How does this operation sign? where the signature?  I try : URI=https://bittrex.com/api/v2.0/market/TradeBuy?apikey=xxxxxxx&nonce=1533282845&marketName=USDT-BTC&orderType=LIMIT&quantity=1&rate=1000&timeInEffect=GOOD_TIL_CANCELLED&conditionType=NONE&target=0  but this does not work. Help please!

**Comment by StasTukalo** [comment]
O!!! Its works!!! I stupid dude. Working uri:  URI=https://bittrex.com/api/v2.0/key/market/TradeBuy?apikey=zzxxx&nonce=1533284167&marketName=USDT-BTC&orderType=LIMIT&quantity=0.0007&rate=999&timeInEffect=GOOD_TIL_CANCELLED&conditionType=GREATER_THAN&target=999777

Yeaaaaa!!!!!!!!!! Thanks for all!!!

**Comment by StasTukalo** [comment]
$nonce=time();
$uri='https://bittrex.com/api/v2.0/key/market/TradeBuy?apikey='.$apikey.'&nonce='.$nonce.'&marketName=USDT-BTC&orderType=LIMIT&quantity=0.0007&rate=999&timeInEffect=GOOD_TIL_CANCELLED&conditionType=GREATER_THAN&target=999777';
$sign=hash_hmac('sha512',$uri,$apisecret);
$ch = curl_init($uri);
curl_setopt($ch, CURLOPT_HTTPHEADER, array('apisign:'.$sign));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$res = curl_exec($ch);
$obj = json_decode($res);
$success=$obj->{'success'}; 
$message=$obj->{'message'};
$result=$obj->{'result'};  
$order_id=$result->{'uuid'};
