### ISSUE TITLE
Did Bittrex just block requests?

### ISSUE THREAD

**Issue by skyl** [ericsomdahl/python-bittrex#38]
I've been using this library successfully for a few weeks. All of a sudden, I can't get any api call to return. Interestingly, I can't make a vanilla call via requests either.

I can GET this with a browser: https://bittrex.com/api/v1.1/public/getcurrencies

OTOH, I can't get it using this python-bittrex library. But, also, this is hanging for me right now:

```
In [1]: import requests

In [2]: res = requests.get('https://bittrex.com/api/v1.1/public/getcurrencies')
# ... hangs forever ...
```

I don't know if you can see this:

https://support.bittrex.com/hc/en-us/requests/151188?page=1

**Comment by ericsomdahl** [comment]
I'm not able to reproduce this behavior against the public APIs -- the tests run OK.

However -- my authenticated (Account-level methods) tests are now failing so I am looking into it now

**Comment by skyl** [comment]
I think they fixed it. I can make requests with `requests` and use the API with my keys as usual. I think they must have made a change on their end and changed it back ... weird ...
