### ISSUE TITLE
get_marketsummary returning type list?

### ISSUE THREAD

**Issue by danbianculli** [ericsomdahl/python-bittrex#39]
According to the commenting the get_marketsummary should return a dict, but it's returning a list for me. This is making getting the info into a dataframe difficult. Does anyone have a solution for this?

**Comment by ericsomdahl** [comment]
if you take a look at [the api](https://bittrex.com/Home/Api) both **get_marketsummary** and **get_marketsummaries** both return lists.  I agree that it actually makes more sense for summary to return a singular object -- but the API is what it is.

The general approach of this wrapper is to not provide too much fluff on top of the native Bittrex API. I'm not really in favor of making arbitrary changes or adding unnecessary abstractions that get between you and Bittrex.

If it is an impediment you could just write your own function to wrap around **get_marketsummary** that slices out the first element of the response.
