### ISSUE TITLE
/public/getorderbook

### ISSUE THREAD

**Issue by huahaofeng** [ericsomdahl/python-bittrex#44]
I find the method `get_orderbook(self, market, depth_type, depth=20)` which can be called with parameter `depth`, but finally find out it does not control the length of response.

**Comment by khaman1** [comment]
I have the same problem btw

**Comment by t4ec** [comment]
Looks like, according to official documentation https://bittrex.com/Home/Api, bittrex does not support depth parameter at the moment.

**Comment by ericsomdahl** [comment]
agree with @t4ec -- this is not a bug but the ignored parameter should be removed from the method signature

**Comment by ericsomdahl** [comment]
a new branch exists for API 2.0 support.  In addition to 2.0, the extraneous **depth** parameters are being removed wherever the 1.1 API does not support it anymore
