### ISSUE TITLE
UserWarning: Unknown distribution option: 'modules'

### ISSUE THREAD

**Issue by aReaSa** [ericsomdahl/python-bittrex#48]
hello dear coder
first of all thank you this project 

but i couldnt run it. i install python3.6 and pip install request but when i run the setup.py i have an error like this "

Warning (from warnings module):
  File "C:\Users\Enes\AppData\Local\Programs\Python\Python36-32\lib\distutils\dist.py", line 261
    warnings.warn(msg)
UserWarning: Unknown distribution option: 'modules'

**Comment by BigFav** [comment]
'modules' should be changed to 'py_modules' (or just delete it), and then you will run into the error resolved below.

https://stackoverflow.com/a/19672752

**Comment by ericsomdahl** [comment]
stale issue
