### ISSUE TITLE
APISIGN not provided

### ISSUE THREAD

**Issue by sharkmerry7** [ericsomdahl/python-bittrex#49]
Perhaps Im being an idiot. Ive got the secrets.json file created. If i run Bittrex_tests or any call involving the API. I get {"success":false,"message":"APISIGN_NOT_PROVIDED","result":null}  

I could not find a solution anywhere but most people not complaining about it either so I presume its something stupid Im doing. Can you please help?

**Comment by ericsomdahl** [comment]
Is the secrets file in the tests folder?
