### ISSUE TITLE
AttributeError: module 'urllib' has no attribute 'urlencode'

### ISSUE THREAD

**Issue by hswick** [ericsomdahl/python-bittrex#50]
Seems to be having python3 trouble. 
This stackoverflow issue presents fix: https://stackoverflow.com/questions/28906859/module-has-no-attribute-urlencode
   
 btrx.get_balance("ETH")
  File "/usr/local/lib/python3.6/site-packages/bittrex/bittrex.py", line 292, in get_balance
    return self.api_query('getbalance', {'currency': currency})
  File "/usr/local/lib/python3.6/site-packages/bittrex/bittrex.py", line 62, in api_query
    request_url += urllib.urlencode(options)
AttributeError: module 'urllib' has no attribute 'urlencode'

**Comment by hswick** [comment]
Noticed this was already implemented.

**Comment by hswick** [comment]
I have tried this on version 0.1.3 and 0.1.4 and still receiving same error.

**Comment by LeeHJones** [comment]
I'm getting this as well from get_ticker().

**Comment by JeffWScott** [comment]
I don't think this has been fixed yet.  Python versions are such a mess.

**Comment by TalhaAsmal** [comment]
This has been fixed over a year ago. Please try pulling the latest code and installing using the following steps:

1. git clone https://github.com/ericsomdahl/python-bittrex.git
2. cd python-bittrex
3. python setup.py install

**Comment by BTuyn** [comment]
I am still getting this problem with the latest code.

**Comment by TalhaAsmal** [comment]
Hi @BTuyn 

Can you please provide the steps you followed to install the package?

**Comment by BTuyn** [comment]
Sorry, problem has been resolved after doing: `from bittrex.bittrex import Bittrex` instead of `from bittrex import Bittrex`

**Comment by TalhaAsmal** [comment]
This issue seems resolved.

**Comment by zilton7** [comment]
Any solutions here? I am also getting same error...
