### ISSUE TITLE
Cannot import name 'Bittrex'

### ISSUE THREAD

**Issue by Ocuatrec** [ericsomdahl/python-bittrex#53]
I tried executing this small example and I'm getting the following error:

`ImportError: cannot import name 'Bittrex'`

Is it something I'm doing wrong?

This is my code:
```
from bittrex import Bittrex

btx = Bittrex(<key>, <key_secret>)

print(btx.get_balance("BTC"))
```

**Comment by clu8** [comment]
Try `from bittrex.bittrex import Bittrex`

**Comment by Ocuatrec** [comment]
Thank you!
