### ISSUE TITLE
TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)

### ISSUE THREAD

**Issue by blakejoy** [ericsomdahl/python-bittrex#54]
Error on signature for api_query, 

TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)

**Comment by mfurlend** [comment]
same issue...

**Comment by blakejoy** [comment]
Where is the error coming from ? I forgot, but I definitely fixed it.

**Comment by blakejoy** [comment]
if its the signature it should be:

`signature = hmac.new(b'{self.api_secret}', request_url.encode('utf-8'), hashlib.sha512).hexdigest()
`
