### ISSUE TITLE
get_market_history doesn't actually support count

### ISSUE THREAD

**Issue by brousch** [ericsomdahl/python-bittrex#55]
Bittrex.get_market_history has a count parameter, however the Bittrex API doesn't support that parameter. The method always returns 200 results.

https://github.com/ericsomdahl/python-bittrex/blob/master/bittrex/bittrex.py#L236
https://bittrex.com/home/api , scroll to /public/getmarkethistory

**Comment by ericsomdahl** [comment]
@brousch agreed - the API used to support it but the parameters were removed.

A branch has started on a 2.0 API update.  In addition to 2.0, extraneous **depth** parameters are being removed from the 1.1 endpoints

**Comment by ericsomdahl** [comment]
there are several places where there is an extraneous depth **parameter**.  They are all being removed as part of the 2.0 support
