### ISSUE TITLE
How to Scraping and Sorting the Prices According to the Quantity Amount of ETH from API?

### ISSUE THREAD

**Issue by adi-pratama** [ericsomdahl/python-bittrex#60]
How to Scraping and Sorting the Prices According to the Quantity Amount of ETH from API? 

API: https://bittrex.com/api/v1.1/public/getorderbook?market=BTC-ETH&type=both 

Image of API: https://s26.postimg.org/5ome3wqzt/Screenshot_93.png 

Design Demo: https://s26.postimg.org/d1x6p4lnt/Screenshot_92.png

**Comment by ericsomdahl** [comment]
what to do with the data you get from the API is out of scope for the connector library
