### ISSUE TITLE
Set of Altcoins valuations to BTC

### ISSUE THREAD

**Issue by Jzarecta** [ericsomdahl/python-bittrex#7]
I am building a bot, looking into using Bittrex API, wonder how can I get a list of a set of altcoins. Like:

```
myset.json { 'btc', 'ltc', 'rby', 'efl', 'dash' ..}
$python yourscript.py myset.json
LTC: 0.0001
RBY: 0.000023
EFL: 0.000012
....
```

Is this possible with your calls?

**Comment by avbanks** [comment]
*Late post I know but why is this still open?  This is provided by the get_markets method.
