### ISSUE TITLE
Unable to install using git repository

### ISSUE THREAD

**Issue by steelliberty** [ericsomdahl/python-bittrex#73]
After cloning and running python setup.py install -- I get the bittrex directory and .egg in site-packages -- but bittrex module contains no code.  So from bittrex import Bittrex produces error "Can't import Bittrex" --  So I tried using pip install git+https//github... ( after uninstalling by hand) and the same thing happens, pip installs the code but the referred bittrex module is apparently empty.  However the bittrex.py file is correct in the bittrex directory of site-packages. 

So I am going to just use the bittrex.py file locally and import it that way..

**Comment by slazarov** [comment]
I did the following:

Add the code to bittrex/__init__py.
`from bittrex.bittrex import *`

Then access it like that:
```
import bittrex
client=bittrex.Bittrex(api_key='key', api_secret='secret', api_version=bittrex.API_V2_0)
summary = client.get_market_summaries()['result']
```

**Comment by TalhaAsmal** [comment]
This should also work: 
`from bittrex.bittrex import Bittrex`

**Comment by ericsomdahl** [comment]
@steelliberty if this is still an issue please try using pip -- we are now (as of 0.2.1) deploying tags to PyPi.

pip install python-bittrex

**Comment by ericsomdahl** [comment]
this seems stale so I'm closing it
