### ISSUE TITLE
Publish to pypi

### ISSUE THREAD

**Issue by mihneadb** [ericsomdahl/python-bittrex#76]
Hello,

Thanks for this lib! It would be of great help if you published it to Pypi.

Best,
Mihnea

**Comment by meister245** [comment]
Hello,

I second this, I wanted to update the package with pip, but I realized the 2.0 api support is not published yet.

Best,
Zsolt

**Comment by ericsomdahl** [comment]
we are almost there but our package name is currently in use :/
 
@psychopenguin :  would you please remove your deploy of the python-bittrex an PyPi so that this repo can use that name?

**Comment by ericsomdahl** [comment]
PR #92 has been merged to master so removal of @psychopenguin's upload from PyPi is the only blocker to this

**Comment by psychopenguin** [comment]
Hi there! I've removed the project from PyPi. Feel free to upload it with your own account! :)

Cheers!

**Comment by ericsomdahl** [comment]
@psychopenguin thanks!

The deed is done and tag v0.2.1 can be deployed from PyPi
