### ISSUE TITLE
Do a better job of maintaining this repo

### ISSUE THREAD

**Issue by ericsomdahl** [ericsomdahl/python-bittrex#79]
I apologize to everyone for my lack of attention on this repo.  Personal life/work/etc interferes.

So I would like to know who would wish to be a collaborator on this repo?  The following users have been active in the Issues or have submitted PRs in the recent past:  @skyl, @Scribilicious , @ThierryDeruyttere, @TalhaAsmal , @cdgriffith 

If you are interested please reply in this issue.  Others not mentioned above are also welcome.

**Comment by slazarov** [comment]
Also interested in making contributions.

**Comment by CNiemans** [comment]
Hi Eric
I have a kinded of busy schedule too , but im interressed in the topic, id
be glad to help you on lower importance topics
Simon

**Comment by smechaab** [comment]
Hi Eric,

I plan to use this API for a script so I would be excited to collaborate, within the limits of my skills.
Sémy

**Comment by skyl** [comment]
We're kinda' in limbo until Bittrex officially documents their 2.0 API. I'm interested in contributing to this library. But, I'm also hoping that liquidity on decentralized exchanges improves ;)

**Comment by meister245** [comment]
Hi Eric,
I'm using this library extensively in my projects, would be happy to help and contribute to the library, if it's possible within my skills.

**Comment by TalhaAsmal** [comment]
Hi Everyone,

I'm happy to continue helping as necessary.

**Comment by fraserh** [comment]
@skyl Any news on when 2.0 might be released officially?

**Comment by JeffWScott** [comment]
I'd be interested in making this async.

**Comment by ericsomdahl** [comment]
I'm closing this issue for now -- I am happy to report that @skyl and @TalhaAsmal have come on board as collaborators.

The community around this API is growing and I am hoping that we can do some fun and interesting (and profitable?) things together
