### ISSUE TITLE
ImportError: cannot import name 'Bittrex'

### ISSUE THREAD

**Issue by naintoo** [ericsomdahl/python-bittrex#82]
Hi,

not sure why import error pops after install setup.py

'import bittrex' works fine but

'from bittrex import Bittrex' doesn't work
ImportError: cannot import name 'Bittrex'

Python 3.6.0 |Anaconda 4.3.1 (64-bit)

**Comment by TalhaAsmal** [comment]
Hi @naintoo 

Can you please try 

`from bittrex.bittrex import Bittrex`

**Comment by Moulick** [comment]
Neither `from bittrex.bittrex import Bittrex` nor `from bittrex import Bittrex` is working for me. I even added `from .bittrex import *` to the init.py file and reinstalled from setup.py.
The error I am getting is `AttributeError: module 'bittrex' has no attribute 'Bittrex'`

**Comment by naintoo** [comment]
Thank you TalhaAsmal. I found that i named file “bittrex.py”. I have changed name and now it doesn’t have import issue

**Comment by Moulick** [comment]
@naintoo damn, made the same mistake yesterday. spent over an hour and found I named my file bittrex.py. Such a easy mistake to make
