### ISSUE TITLE
Exception: method call not available under API version API_V2_0

### ISSUE THREAD

**Issue by nekcorp** [ericsomdahl/python-bittrex#85]
Hi,

I have problem, when I use api_version = "API_V2_0" I have this error message : 

`>>> my_Bittrex = Bittrex(None, None ,api_version = "API_V2_0")`
`>>> my_Bittrex.get_balances()`
`Exception: method call not available under API version API_V2_0`

None is respectively my key and my secret key.

But when I use : 
`>>> my_Bittrex = Bittrex(None, None)`
`>>> my_Bittrex.get_balances()`

All it is OK.

What is the problem when I use API_V2_0 ?

Thanks a lot for your help.

**Comment by TalhaAsmal** [comment]
Hi @nekcorp,

Can you please try to initialize the Bittrex API as follows:

```
from bittrex.bittrex import API_V2_0, Bittrex

my_Bittrex = Bittrex(None, None, api_version=API_V2_0
my_Bittrex.get_balances()
```

Note the import of the constant API_V2_0, and the subsequent usage of that constant when initializing the API.

**Comment by nekcorp** [comment]
Hi @TalhaAsmal,

All it is OK !

So it is the first time a see that we can import a variable, usually I import Class or method.

Thanks a lot for your help

**Comment by LachlanB96** [comment]
@nekcorp @TalhaAsmal 

I don't think you can import a variable, but this seems like it is... Anyway, you could also use this line and it would work:

my_Bittrex = Bittrex(None, None, api_version='v2.0')

**Comment by TalhaAsmal** [comment]
@LachlanB96 There's nothing stopping you from importing a variable or, indeed, anything in a Python file. I regularly make use of 'variable' imports for constants across my applications.

**Comment by TalhaAsmal** [comment]
This issue is resolved.
