### ISSUE TITLE
Get currency price in dollars, euro ... 

### ISSUE THREAD

**Issue by nekcorp** [ericsomdahl/python-bittrex#86]
Hi, 

Is it possible to get price of a currency in dollars, euro, or other ?

I have seen in the [API guide](https://bittrex.com/Home/Api), but nothing it is mentionned.

Regards.

**Comment by denigada** [comment]
you can just convert it using a currency converter api. Or get the price using coinmarketcap's api

**Comment by ericsomdahl** [comment]
+1 for @denigada's response

**Comment by nekcorp** [comment]
@denigada Yes off cource but the price on coinmarketcap is not the same on Bittrex and for trading it is not a good way. 

What do you mean about currency converter api ?

Regards.

**Comment by denigada** [comment]
use this api to convert the price you have to any currency you want

fixer.io

**Comment by skyl** [comment]
Bittrex doesn't have fiat. So, usually you would convert to BTC and then get the price of BTC in the fiat of your choice.

```
PRICE_OF_KMD_IN_FIAT = api.get_ticker('BTC-KMD')['result']['Last'] * PRICE_OF_BTC_IN_FIAT
```

**Comment by nekcorp** [comment]
@denigada I want to get dollars or euro values of the BTC or other crypto.

**Comment by nekcorp** [comment]
@skyl This is my problem. 
PRICE_OF_BTC_IN_FIAT it is the value I need to get on Bittrex, but Bittrex does not accept this request for the moment !
