### ISSUE TITLE
get_order_history does not return full order history

### ISSUE THREAD

**Issue by aaronr22** [ericsomdahl/python-bittrex#87]
My code only outputs 29 orders when my full order history downloaded as a CSV from Bittrex has 50+ entries.   The bug could be in my code but I can't figure out where.  It shows all my trades from this month and last month but none from the months prior.

```
from bittrex import API_V2_0, Bittrex
import json

my_bittrex = Bittrex("key", "secret")

list = my_bittrex.get_order_history()

#gets only the 'result' from the returned dict
result = list['result']

for k in result:
    print(k['OrderUuid'])
```

**Comment by TotallyKyle** [comment]
It's a limitation of the bittrex API, they only provide recent trades.

**Comment by jogam5** [comment]
Stuck here as well. For the % of money they charge per trade, with respect to other exchanges, it's a real shame.

**Comment by aaronr22** [comment]
I think the only way to get this would be to download the CSV of your history from the website and then update that CSV.  I cannot figure out how to get the result number values to write to a csv.  This is the code I have, but the CSV just gets filled with: OrderUuid,Exchange,TimeStamp,OrderType,Limit,Quantity,QuantityRemaining,Commission,Price,PricePerUnit,IsConditional,Condition,ConditionTarget,ImmediateOrCancel,Closed
every time with none of the actual data.  How can I get the actual data to the CSV?

```
    data = my_bittrex.get_order_history()
    with open('test.csv', 'w') as f:
        writer = csv.writer(f)
        for line in data:
            print(line)
            writer.writerow(line)
```

**Comment by ericsomdahl** [comment]
@TotallyKyle has the correct answer.
