### ISSUE TITLE
Where is version 2.0 of the API Documented?

### ISSUE THREAD

**Issue by metaperl** [ericsomdahl/python-bittrex#90]
Hello, the python-bittrex docs mention a 2.0 API, but I see no mention of a 2.0 API at [the Bittrex API documentation](https://bittrex.com/Home/Api).

Where can I read the authoritative information on this API?

**Comment by ignacio560** [comment]
Same question!

**Comment by ericsomdahl** [comment]
honestly, I am working off of rumor and the other language bindings for Bittrex (https://github.com/n0mad01/node.bittrex.api for instance)

Once, I recall I had found a bitcointalk.org thread about it but i was unable to find it googling just now.
