### ISSUE TITLE
I'm new in Python, please help

### ISSUE THREAD

**Issue by monomikike** [ericsomdahl/python-bittrex#91]
Hi! 

I'm leraning Python 3.6 now, want to trade in Bittrex. Qould someone explain me, what to install and how? 
I installed bittrex (pip3 install bittrex), downloaded the zip from here, unzipped, run bittrex_testes, but I have an error: ImportError: cannot import name 'API_V2_0'

I tried the following: 
from bittrex import Bittrex

my_bittrex = Bittrex('xxx','xxx') 
my_bittrex.get_markets()
my_bittrex.get_balance('BTC')

No error, but nothing happens. I have bittrex.py in the same directory. 

What am I doing wrong? 

Thanks, 
monomikike

**Comment by ericsomdahl** [comment]
take a look at the tests for examples of how to invoke the differentmethods

https://github.com/ericsomdahl/python-bittrex/blob/master/bittrex/test/bittrex_tests.py

take note of the imports at the top of the file.  Also you must assign the response from the api call to some variable, so that you can use the results of the call.

Good luck

**Comment by monomikike** [comment]
Hi!

Thanks for Your help, trying to figure out the rest... But could You help
me a bit? With the bittrex.get_ticker('BTC-LTC') i get the following:
{'success': True, 'message': '', 'result': {'Bid': 0.0093351, 'Ask':
0.00934433, 'Last': 0.00934433}}

How can I get only an exact part of it, for example the Last price?

Is there an educational site where I can learn these? I used C+ a lot, but
Python seems hard for me...

Thanks,
Miklos

2017-11-21 14:26 GMT+01:00 Eric Somdahl <notifications@github.com>:

**Comment by skyl** [comment]
The method returns a dict. https://www.python-course.eu/dictionaries.php

**Comment by skyl** [comment]
https://docs.python.org/3/tutorial/datastructures.html#dictionaries
