### ISSUE TITLE
how do you check if there is open orders or not?

### ISSUE THREAD

**Issue by denigada** [ericsomdahl/python-bittrex#93]
Hello. Im trying to cancel open orders if there is one, but the code fails. I check it with these two options, but sometimes the first one doesn't work and sometimes the second one doesn't work.

1- len(myBittrex.get_open_orders(currencyPair)["result"]) != 0
2- myBittrex.get_open_orders(currencyPair)["result"] != None

What is the proper way to check if there is open orders or not for a specific currency pair?

**Comment by skyl** [comment]
Maybe you don't have your API keys set sometimes or you have a flaky network connection or there is another error. You could do something like:

```
resp = api.get_open_orders(currencyPair)
if resp['success']:
    return len(resp['result'])
```

An error `resp` would look something like this:

```
Out[1]: {'message': 'APIKEY_INVALID', 'result': None, 'success': False}
```

In the case of an error, you don't know if you have orders or not. I might just let the `TypeError` go to the caller. Depends on what you're trying to do...
