### ISSUE TITLE
cancel doesn't work with API v 2.0

### ISSUE THREAD

**Issue by flepied** [ericsomdahl/python-bittrex#96]
I always get this error:

{'success': False, 'message': 'NO_API_RESPONSE', 'result': None}

**Comment by ericsomdahl** [comment]
Are you up to date with the most current version of this repo?  Commit d25b5dd31f3d836882734ff6f50f7d9944caac94 has a fix that addresses the Cancel bug.

**Comment by flepied** [comment]
Yes you are right. I was just behind. Sorry.
