### ISSUE TITLE
printing Last price from ticker

### ISSUE THREAD

**Issue by Mantas779** [ericsomdahl/python-bittrex#97]
from bittrex import Bittrex

my_bittrex = Bittrex(None, None)

ticker = my_bittrex.get_ticker('USDT-BTC')

print (ticker)
-----------------------------------------------------------------
{'message': '', 'success': True, 'result': {'Last': 10930.0, 'Ask': 10930.0, 'Bid': 10924.535}}
---------------------------------------------------------------------------------------------

Works fine ,  but now i want to print only 'Last' 

I tried all kind of possibilities , i mix up lists , arrays with dictionaries.
Can someone show me a example?

I got it : 

tick = ticker['result']
print (tick['Last'])

**Comment by skyl** [comment]
Correct. These are regular Python dictionaries. https://docs.python.org/3/tutorial/datastructures.html#dictionaries
