### ISSUE TITLE
get_marketsummary() gives non consistent results

### ISSUE THREAD

**Issue by nicochidt** [ericsomdahl/python-bittrex#98]
When I call get_marketsummary() I get different results in different calls: 

`api = Bittrex(None, None, api_version=API_V2_0)`

`api.get_marketsummary("USDT-BTC")`

`{u'message': u'', u'result': {u'PrevDay': 0.000574, u'Volume': 3623482.77570515, u'Last': 0.00062741, u'OpenSellOrders': 9439, u'TimeStamp': u'2017-12-05T13:18:16.727', u'Bid': 0.00062733, u'Created': u'2016-08-10T23:26:39.657', u'OpenBuyOrders': 3414, u'High': 0.00069376, u'MarketName': u'BTC-STRAT', u'Low': 0.00056665, u'Ask': 0.00062741, u'BaseVolume': 2309.05006317}, u'success': True}`

`api.get_marketsummary("USDT-BTC")`

`{u'message': u'', u'result': {u'PrevDay': 3.517e-05, u'Volume': 2698632.06415573, u'Last': 3.696e-05, u'OpenSellOrders': 1427, u'TimeStamp': u'2017-12-05T13:20:28.6', u'Bid': 3.67e-05, u'Created': u'2016-08-25T21:23:15.27', u'OpenBuyOrders': 335, u'High': 4.3e-05, u'MarketName': u'BTC-SYNX', u'Low': 3.4e-05, u'Ask': 3.686e-05, u'BaseVolume': 102.34351583}, u'success': True}`

`api.get_marketsummary("USDT-BTC")`

`{u'message': u'', u'result': {u'PrevDay': 0.00013334, u'Volume': 1579268.40532364, u'Last': 0.00016369, u'OpenSellOrders': 2762, u'TimeStamp': u'2017-12-05T13:20:14.257', u'Bid': 0.00016385, u'Created': u'2015-01-25T03:00:35.143', u'OpenBuyOrders': 1136, u'High': 0.00017925, u'MarketName': u'BTC-NXS', u'Low': 0.0001328, u'Ask': 0.0001647, u'BaseVolume': 250.10025334}, u'success': True}`

`api.get_marketsummary("USDT-BTC")`

`{u'message': u'', u'result': {u'PrevDay': 0.02700605, u'Volume': 33594.74326774, u'Last': 0.02553054, u'OpenSellOrders': 17158, u'TimeStamp': u'2017-12-05T13:20:37.85', u'Bid': 0.02551762, u'Created': u'2017-11-20T21:49:15.983', u'OpenBuyOrders': 1096, u'High': 0.027445, u'MarketName': u'BTC-BTG', u'Low': 0.02551762, u'Ask': 0.02553054, u'BaseVolume': 890.59214491}, u'success': True}`

So asking for USDT-BTC I get: BTC-STRAT, BTC-SYNX, BTC-NXS, BTC-BTG. Sometimes I also get USDT-BTC.

Using curl I get each time the same (and correct) market:

`curl https://bittrex.com/api/v1.1/public/getmarketsummary?market=USDT-BTC
{"success":true,"message":"","result":[{"MarketName":"USDT-BTC","High":11790.95000000,"Low":10781.00000000,"Volume":5173.81212339,"Last":11745.00000000,"BaseVolume":59117879.38667940,"TimeStamp":"2017-12-05T13:10:24.187","Bid":11745.00000000,"Ask":11747.00000000,"OpenBuyOrders":16949,"OpenSellOrders":3678,"PrevDay":10950.00009908,"Created":"2015-12-11T06:31:40.633"}]}`

**Comment by ericsomdahl** [comment]
if you try 
```
api = Bittrex(None, None, api_version=API_V1_1)
```
Do you get the same results?  i suspect this is a problem on Bittrex's side.

**Comment by nicochidt** [comment]
you nailed it! It's definitely a bittrex issue. No problem with the API_V1_1. 

Thanks!
